### PR TITLE
Adjusted web page for mobile use

### PR DESCRIPTION
**Pull request by s-weigand**
Thanks for the nice cheatsheet 😃 
So I saw you wanted help for `Better mobile experience` and I made some changes:
* added viewport meta tag for the fonts to scale properly
* moved the `*.js` files to the end of the html document, to guarante that the document is ready before they get executed
* changed the way links are inserted in the headings, so that there is no need for absolute positions and negativ margins and a min-width for the html document
* changed the url for the font so it also works locally
* h1 width and silly walks banner now  scale with the screen width

I did tests it with chrome and firefox devtools.

### CODE REVIEW

**Comment by gto76** [comment]
Wow, amazing!
Only problem is that the h2 titles and the code examples are indented to the right but h3 titles and text are unaffected.
Is it possible to have the exact same layout as before?

**Comment by s-weigand** [comment]
Thanks 😄 
I adjusted the indentation, hope I got all as in the original layout.

**Comment by s-weigand** [comment]
Sorry for the whitespace changes, it's my default editor setting to trim tailing whitespaces.

**Comment by s-weigand** [comment]
And here is a screenshot for mobile resolution

python-cheatsheet_screene

**Comment by gto76** [comment]
Thanks.
Only problem I still have is how subtitles and text are indented to far:
Screen Shot 2019-03-27 at 15 15 30
compared to how it used to be:
Screen Shot 2019-03-27 at 15 16 32

**Comment by gto76** [comment]
Also it would be nice if the mobile view could show a bit more columns.
Now it shows only around 34-36 lines of code and I would prefer more around 45-55 range.
This way first columns of the comments would be visible for most examples and for text would be still big enough, at least for my eyes.

**Comment by gto76** [comment]
Anyways, thank again.
And please inform me if you don't have time or interest for my requests, in which case I will paste them into TODO Issue.

**Pull request merged**
