### PR TITLE
I have added Selenium reference code in your cheatsheet

### PR DESCRIPTION
**Pull request by bigpythonimish**

### CODE REVIEW

**Comment by gto76** [comment]
Nice, I knew I was missing something :)
Please keep this pull request open, while I decide in how to include it.

**Comment by bigpythonimish** [comment]
Sure, I'd love to include in more examples in reference to headed and headerless scraping. Will be helpful to the community. Also, we should probably add Scapy too.

Best,
Nimish Verma

**Comment by bigpythonimish** [comment]
@gto76  I see you have included my commit changes in master, kindly merge this branch with the master branch. Thanks!

**Comment by gto76** [comment]
I reformatted the code a little and just made my own commit. Hope you're OK with that.
Thanks again.

**Pull request closed without merging**
