### PR TITLE
Add a table of contents

### PR DESCRIPTION
**Pull request by pierrepinard-2**
Hi, I just wanted to add a table of contents to the page, to ease navigation and discovery.
I didn't test the static website part however (style for the new table of contents).
Thank you for this great cheatsheet!

### CODE REVIEW

**Comment by gto76** [comment]
Thanks.
I will try this commit out later, when everything settles, but I will probably remove it after.
I don't think it will look right and I don't want to clutter the top of the page. I might find some compromise though.

Also if you want to test it, you need to go to your fork's settings and enable GitHub pages (master branch). And also you need to change `GITHUB` constant in `web/script.js` to your URL.

**Comment by pierrepinard-2** [comment]
Allright, thank you for the details.
Feel free to reach me later for any further modifications on the subject.

**Comment by gto76** [comment]
I added a table of contents.

**Comment by pierrepinard-2** [comment]
Allright, thank you!

**Pull request closed without merging**
